# Generated by Django 6.0.2 on 2026-02-26 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('empresa', models.CharField(max_length=150)),
                ('estado', models.CharField(default='ABIERTA', max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NRMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nr', models.CharField(max_length=20, unique=True)),
                ('ciudad', models.CharField(max_length=150)),
                ('zona', models.CharField(max_length=150)),
                ('fecha_trabajo', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reclamo', models.CharField(max_length=20, unique=True)),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=150)),
                ('zona', models.CharField(max_length=150)),
                ('fecha_reclamo', models.DateField()),
                ('descripcion_falla', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemNRMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.FloatField()),
                ('unidad_medida', models.CharField(max_length=50)),
                ('nr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.nrmateriales')),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_plano_deposito', models.CharField(max_length=50, unique=True)),
                ('archivo', models.FileField(upload_to='planos/')),
                ('texto_ocr', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='EN_REVISION', max_length=30)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('carpeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carpeta')),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150)),
                ('accion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plano')),
            ],
        ),
        migrations.AddField(
            model_name='nrmateriales',
            name='reclamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reclamo'),
        ),
    ]
