# Generated by Django 6.0.2 on 2026-02-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='fecha_plano',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='nr_detectados',
            field=models.TextField(blank=True, null=True),
        ),
    ]
