# Generated by Django 6.0.2 on 2026-02-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_plano_fecha_plano_plano_nr_detectados'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='nr_desconocidos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='nr_validos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
