# Generated by Django 6.0.2 on 2026-02-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_plano_motivo_plano_nr_desconocidos_plano_nr_validos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nrmateriales',
            name='ciudad',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='nrmateriales',
            name='zona',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
