# Generated by Django 6.0.2 on 2026-03-12 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_nrmateriales_ciudad_alter_nrmateriales_zona'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaContratista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('ruc', models.CharField(blank=True, max_length=30, null=True)),
                ('contacto', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa contratista',
                'verbose_name_plural': 'Empresas contratistas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='StockMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_material', models.CharField(max_length=200)),
                ('codigo_material', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('cantidad_disponible', models.FloatField(default=0)),
                ('unidad', models.CharField(default='unidad', max_length=50)),
                ('stock_minimo', models.FloatField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock de material',
                'verbose_name_plural': 'Stock de materiales',
                'ordering': ['nombre_material'],
            },
        ),
        migrations.AlterModelOptions(
            name='auditoria',
            options={'ordering': ['-fecha'], 'verbose_name': 'Auditoría', 'verbose_name_plural': 'Auditorías'},
        ),
        migrations.AlterModelOptions(
            name='carpeta',
            options={'ordering': ['-anio', '-mes', '-fecha_creacion']},
        ),
        migrations.AlterModelOptions(
            name='itemnrmateriales',
            options={'ordering': ['descripcion'], 'verbose_name': 'Ítem de NR Materiales', 'verbose_name_plural': 'Ítems de NR Materiales'},
        ),
        migrations.AlterModelOptions(
            name='nrmateriales',
            options={'ordering': ['-fecha_trabajo', 'numero_nr'], 'verbose_name': 'NR Materiales', 'verbose_name_plural': 'NR Materiales'},
        ),
        migrations.AlterModelOptions(
            name='plano',
            options={'ordering': ['-fecha_carga']},
        ),
        migrations.AlterModelOptions(
            name='reclamo',
            options={'ordering': ['-fecha_reclamo', 'numero_reclamo']},
        ),
        migrations.AddField(
            model_name='auditoria',
            name='carpeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='core.carpeta'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='entidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='entidad_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='codigo_carpeta',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='creada_por',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='eliminada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='observacion_general',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemnrmateriales',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nrmateriales',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plano',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='fecha_procesamiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='nr_desconocidos_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plano',
            name='nr_detectados_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plano',
            name='nr_validos_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plano',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='procesado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plano',
            name='procesado_por',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='accion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='core.plano'),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_REVISION', 'En revisión'), ('CERRADA', 'Cerrada'), ('OBSERVADA', 'Observada')], default='ABIERTA', max_length=30),
        ),
        migrations.AlterField(
            model_name='nrmateriales',
            name='reclamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nr_materiales', to='core.reclamo'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='carpeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='core.carpeta'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='estado',
            field=models.CharField(choices=[('EN_ESPERA', 'En espera'), ('EN_REVISION', 'En revisión'), ('EN_VERIFICACION', 'En verificación'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='EN_REVISION', max_length=30),
        ),
        migrations.AddField(
            model_name='reclamo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos', to='core.empresacontratista'),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carpetas', to='core.empresacontratista'),
        ),
        migrations.CreateModel(
            name='ResultadoValidacionPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_detectado', models.CharField(max_length=30)),
                ('nr_normalizado', models.CharField(blank=True, max_length=30, null=True)),
                ('estado_resultado', models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('EN_VERIFICACION', 'En verificación')], default='EN_VERIFICACION', max_length=30)),
                ('ciudad_ok', models.BooleanField(default=False)),
                ('zona_ok', models.BooleanField(default=False)),
                ('fecha_ok', models.BooleanField(default=False)),
                ('motivo_resultado', models.TextField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('nr_materiales_encontrado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_validacion', to='core.nrmateriales')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_validacion', to='core.plano')),
                ('reclamo_encontrado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_validacion', to='core.reclamo')),
            ],
            options={
                'verbose_name': 'Resultado de validación de plano',
                'verbose_name_plural': 'Resultados de validación de planos',
                'ordering': ['id'],
            },
        ),
    ]
