# Generated by Django 6.0.2 on 2026-04-04 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadovalidacionplano',
            name='estado_resultado_manual',
            field=models.CharField(blank=True, choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('EN_VERIFICACION', 'En verificación')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='resultadovalidacionplano',
            name='fecha_revision_manual',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultadovalidacionplano',
            name='fue_revisado_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultadovalidacionplano',
            name='materiales_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultadovalidacionplano',
            name='materiales_requieren_revision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultadovalidacionplano',
            name='motivo_revision_manual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultadovalidacionplano',
            name='revisado_por',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='MaterialDetectadoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('cantidad_original', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad_original', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_original', models.CharField(blank=True, max_length=200, null=True)),
                ('cantidad_editada', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad_editada', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_editada', models.CharField(blank=True, max_length=200, null=True)),
                ('fue_editado', models.BooleanField(default=False)),
                ('editado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_edicion', models.DateTimeField(blank=True, null=True)),
                ('coincide_con_bd', models.BooleanField(default=False)),
                ('observacion_revision', models.TextField(blank=True, null=True)),
                ('resultado_validacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_detectados', to='core.resultadovalidacionplano')),
            ],
            options={
                'verbose_name': 'Material detectado del plano',
                'verbose_name_plural': 'Materiales detectados del plano',
                'ordering': ['resultado_validacion', 'orden', 'id'],
            },
        ),
    ]
