# Generated by Django 6.0.2 on 2026-04-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_resultadovalidacionplano_estado_resultado_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadovalidacionplano',
            name='ciudad_plano_editada',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resultadovalidacionplano',
            name='ciudad_plano_original',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resultadovalidacionplano',
            name='editado_manual_por',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resultadovalidacionplano',
            name='fecha_edicion_manual',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultadovalidacionplano',
            name='fecha_plano_editada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultadovalidacionplano',
            name='fecha_plano_original',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultadovalidacionplano',
            name='fue_editado_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultadovalidacionplano',
            name='motivo_edicion_manual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resultadovalidacionplano',
            name='zona_plano_editada',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='resultadovalidacionplano',
            name='zona_plano_original',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
