# Generated by Django 6.0.2 on 2026-07-09 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_resultadovalidacionplano_ciudad_plano_editada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='referencia_plano',
            field=models.CharField(blank=True, help_text='Referencia descriptiva opcional del plano.', max_length=150, null=True),
        ),
    ]
