# Generated by Django 6.0.2 on 2026-07-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_plano_referencia_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='fecha_revision_administrativa_cerrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='motivo_revision_administrativa_cerrada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='revision_administrativa_cerrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plano',
            name='revision_administrativa_cerrada_por',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
